### ISSUE TITLE
Bug: Illegal Characters in Path Exception / Can't Upload Folders? / Restart Explorer During Setup

### ISSUE THREAD

**Issue by SnabbSpelare** [SamuelTulach/VirusTotalUploader#147]
### Bug: Illegal Characters in Path Exception

See the end of this message for details on invoking just-in-time (JIT) debugging instead of this dialog box.

![VTU Error Message Screenshot](https://github.com/user-attachments/assets/7fc4913e-ff1a-486d-a449-dcfdaff65570) or https://prnt.sc/InKnuhBXLsnn

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at uploader.Utils.GetMD5(String file) in Q:\VirusTotalUploader\uploader\uploader\Utils.cs:line 17
   at uploader.UploadForm.UploadForm_Load(Object sender, EventArgs e) in Q:\VirusTotalUploader\uploader\uploader\UploadForm.cs:line 170
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9256.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
uploader
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Samuel%20Tulach/VirusTotalUploader/uploader.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
DarkUI
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Samuel%20Tulach/VirusTotalUploader/DarkUI.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Program%20Files%20(x86)/Samuel%20Tulach/VirusTotalUploader/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

### Can't Upload Folders?

In my experience, I would really like to upload all files within a folder or directory, specifically in my case the "_Redist" folder, which contains various DirectX and other requirement setup files for running games. However, this feature is nonexistent. Is there a reason for this?

**The issue below may just be a misjudgment on my end, but I have included it nonetheless.**

### Restart Explorer During Setup or Else Missing in Context Menu

I'd highly recommend automatically restarting Explorer by using `taskkill` and then reopening it. I only know how to do this via a batch script or alternatively through Task Manager. If you don't do this, the changes won't appear until you restart the OS, which is highly unnecessary when it's such a simple fix. This only has to be done once after or during installation, after it's been added to Windows 11's Context Menu. I initially didn't know it only worked with files and not folders, so when I right-clicked, it didn't show me the expected options.

**Comment by gordenbrown51** [comment]
i got a similar problem... if I try to upload a dll file from Windows/System32 folder i got this message... is it possible to upload a whole folder to virustotal? @SnabbSpelare

**Comment by tnhung2011** [comment]
You can try a way around illegal characters by creating a symlink. For the context menu item, casual users can just logout then login again. This has the same effect as restarting File Explorer.

**Comment by SnabbSpelare** [comment]
> i got a similar problem... if I try to upload a dll file from Windows/System32 folder i got this message... is it possible to upload a whole folder to virustotal? [@SnabbSpelare](https://github.com/SnabbSpelare)

### You can scan a folder on VirusTotal!

Sorry to hear about this problem still there, and yes you can [upload a folder to VirusTotal](https://www.virustotal.com/gui/home/upload) containing .dll's if you want to check them. Just go to their site and drag the folder into the center and drop it. Then it will ask you to confirm, press _'confirm'_.

I would do that with any copy of a game from a e.g. **old disc or before installing software that trigger potentially false detection**.

To be more specific about uploading to VirusTotal; there is a limit to file size or number of files if I remember it right. There could be a way around that like using [API](https://docs.virustotal.com/docs/api-scripts-and-client-libraries) _(which is free to an extend)_ or paying for their subscription? I checked a small folder I had with a few files _**(and it worked for me at least)**_. Just know that I am pretty sure everything you upload can be accessible by anyone who is paying for VirusTotal... _As those who use their subscription to access advanced features._ Can't speak from experience but from I gathered that's how it may be for you today.


> You can try a way around illegal characters by creating a symlink. For the context menu item, casual users can just logout then login again. This has the same effect as restarting File Explorer.

Thank you! I haven't tried that yet. It sounds plausible, and I appreciate the tip, but I probably won't get around to checking it out anytime soon—admittedly, I don't use VT that much nowadays.
