### ISSUE TITLE
System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by Yousha** [SamuelTulach/VirusTotalUploader#22]
Can´t read from file! Please check if it is not open by another process or check if you have permissions to read it.

```OE: System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Wise\Memory Optimizer\WiseMemoryOptimzer.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode)
   at VirusTotal_Uploader.Form1.UploadFile(String file, String apikey) in H:\Desktop\Windows\Develop\.Net\Application\VirusTotalUploader-master\VirusTotal Uploader\VirusTotal Uploader\VirusTotal Uploader\Form1.cs:line 164```

**Comment by SamuelTulach** [comment]
Closing this issue since it was associated with the old version of uploader. The entire program had [a large recode](https://github.com/SamuelTulach/VirusTotalUploader/commit/c8a8b4c44ac3705607c017e36e6b76f6fab17e48). Please reopen this issue if it persists in the new version as well.
