### ISSUE TITLE
Upload from context menu failed because Settings.ini is not found in the same folder

### ISSUE THREAD

**Issue by zypA13510** [SamuelTulach/VirusTotalUploader#3]
I got a .net exception when trying to upload a file from the context menu.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
IniParser.Exceptions.ParsingException: Could not parse file Settings.ini while parsing line number 0 with value '' - IniParser version: 2.5.2.0 ---> System.IO.FileNotFoundException: Could not find file 'E:\Downloads\Settings.ini'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at IniParser.FileIniDataParser.ReadFile(String filePath, Encoding fileEncoding)
   --- End of inner exception stack trace ---
   at IniParser.FileIniDataParser.ReadFile(String filePath, Encoding fileEncoding)
   at VirusTotal_Uploader.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
VirusTotal Uploader
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/*/AppData/Local/Apps/2.0/Z28ZV5B7.JCZ/6PVA0364.152/viru..tion_7aa9bb788a37f660_0001.0000_3336c4c41e0a78a2/VirusTotal%20Uploader.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
INIFileParser
    Assembly Version: 2.5.2.0
    Win32 Version: 2.5.2
    CodeBase: file:///C:/Users/*/AppData/Local/Apps/2.0/Z28ZV5B7.JCZ/6PVA0364.152/viru..tion_7aa9bb788a37f660_0001.0000_3336c4c41e0a78a2/INIFileParser.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```
(Username in path is redacted as `*`.)
I have installed by running `setup.exe` as admin, and after setup, I have configured API key and added the context menu. Then I tried to scan a file in `E:\Downloads\` and the exception appeared.

Running from start menu and then use drag-n-drop works fine.

**Comment by SamuelTulach** [comment]
Thank you for your report! This issue started in new update. Here is the code causing it:

```
if (!File.Exists(AppDomain.CurrentDomain.BaseDirectory + "Settings.ini")) // Using AppDomain so file is found
            {
                MessageBox.Show(lang.GetString("No settings file found!\n\nThis is because you probably opened this app for first time. Please go to settings and add API key."), lang.GetString("Error"), MessageBoxButtons.OK, MessageBoxIcon.Error);
            } else
            {
                var parser = new FileIniDataParser();
                IniData data = parser.ReadFile("Settings.ini"); // Does not using it, so the error appears
                api = data["General"]["ApiKey"];
                theme = data["General"]["Theme"];
}
```

It is now fixed with [latest commit](https://github.com/SamuelTulach/VirusTotalUploader/commit/453bea7841ce30d0063c5a08b71c0ded60444fa0). Can you please try latest [version compiled from master branch](https://ci.appveyor.com/project/SamuelTulach/virustotaluploader/build/artifacts)?

**Comment by luboq** [comment]
I also found it several days ago and thought it's my PC's problem, so didn't report it. Turns out it's a bug!
already tested it and yeah, the version compiled from master branch fix it.
